# ==============================================================================
# Arquivo de Configuração do Ambiente Conda - Projeto POM
# ==============================================================================
#
# Este arquivo define todas as dependências necessárias para o projeto.
# É uma alternativa ao setup_environment.sh que permite criar o ambiente
# de forma mais declarativa.
#
# Uso:
#   conda env create -f environment.yml
#
# Para atualizar um ambiente existente:
#   conda env update -f environment.yml --prune
#
# Para remover o ambiente:
#   conda env remove -n pom
#
# ==============================================================================

name: pom

channels:
  - conda-forge
  - defaults

dependencies:
  # Python base
  - python=3.10
  
  # Dependências principais
  - numpy>=1.20.0
  - scipy>=1.7.0
  - xarray>=0.19.0
  - netcdf4>=1.5.0
  
  # Visualização
  - matplotlib>=3.3.0
  
  # Utilidades adicionais (opcionais)
  - ipython  # Shell interativo melhorado
  - jupyter  # Para notebooks (se necessário no futuro)
  
  # Ferramentas de desenvolvimento (opcional)
  # - pytest  # Para testes unitários
  # - black   # Para formatação de código
  # - flake8  # Para linting

  # Pacotes via pip (se necessário)
  - pip
  - pip:
    # Adicione aqui pacotes que só estão disponíveis via pip
    # - algum-pacote-especifico
